/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: Lorna Inman (https://sketchfab.com/LornaInman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/peepal-tree-a2d43c68161947aabea36dbbd6c5ea74
Title: Peepal Tree
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.brush_MatteHull} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.brush_Icing} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.brush_CelVinyl} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.brush_CelVinyl} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.brush_CelVinyl} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.brush_CelVinyl} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.brush_DoubleTaperedMarker} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.brush_CoarseBristles} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
